name: Update Repo
on:
  workflow_dispatch:
       
    schedule:
    - cron: "0 15 * * 1-5"
  
jobs:
  update-component:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3 

      - name: Check work folder
        run: pwd

      - name: Update identity
        run: git config --global user.email "satishbraju@gmail.com" && git config --global user.name "satishbraju"

      - name: Update Repo
        run: git submodule update --init --remote

      - name: Commit chnages
        run: git add . && git commit -m "update new version" && git push
   
      - name: Dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
            owner: 'satishbraju',
            repo: 'Release',
            workflow_id: 'update_repo.yaml',
            ref:'main'
            })
  